import { db } from "@/lib/firebase";
import { doc, setDoc } from "firebase/firestore";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    const estadoMesas = {
      mesaAdentro: [
        {
          codigo: "MESA_001",
          numero: 1,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 41300,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_002",
          numero: 2,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 14160,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_003",
          numero: 3,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 14160,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_004",
          numero: 4,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_005",
          numero: 5,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_006",
          numero: 6,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 41300,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_007",
          numero: 7,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_008",
          numero: 8,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_009",
          numero: 9,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_010",
          numero: 10,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_011",
          numero: 11,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_012",
          numero: 12,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
      ],
      mesaAdentro2: [
        {
          codigo: "MESA_B13",
          numero: 13,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 18880,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_B14",
          numero: 14,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_B15",
          numero: 15,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_B16",
          numero: 16,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "Efectivo",
          total: 17700,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_B17",
          numero: 17,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_B18",
          numero: 18,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
      ],
      mesaAfuera: [
        {
          codigo: "MESA_AF19",
          numero: 19,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_AF20",
          numero: 20,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_AF21",
          numero: 21,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
        {
          codigo: "MESA_AF22",
          numero: 22,
          estado: "libre",
          cliente: null,
          productos: [],
          metodoPago: "",
          total: 0,
          hora: "",
          fecha: "",
        },
      ],
    };

    await setDoc(doc(db, "tables", "estadoMesas"), estadoMesas);

    return NextResponse.json({
      success: true,
      message: "Datos insertados correctamente",
    });
  } catch (err) {
    console.error("Error insertando datos:", err);
    return NextResponse.json(
      { error: "Error al insertar datos" },
      { status: 500 }
    );
  }
}
